"""Re-export Kai from horizontal domain. Prefer importing from app.domain.kai."""
from app.domain.kai import (
    KaiAgentService,
    VetResult,
    GuidanceResult,
    ReplyPublicSoloResult,
    UnderstandScreenshotResult,
    ScreenshotMessageAnalysis,
    update_context,
    vet_message,
    get_guidance,
    extract_chat_from_screenshots,
    understand_screenshot_conversation,
    analyze_screenshot_messages_for_revisions_and_guidance,
    analyze_screenshot_communication_and_suggest,
    reply_private,
    reply_public_solo,
    extract_user_preferences,
    detect_lounge_intention,
    generate_activity_recommendations,
    generate_repair_vouchers,
    generate_love_map_questions_for_profile,
    generate_things_to_find_out,
)

__all__ = [
    "KaiAgentService",
    "VetResult",
    "GuidanceResult",
    "ReplyPublicSoloResult",
    "UnderstandScreenshotResult",
    "ScreenshotMessageAnalysis",
    "update_context",
    "vet_message",
    "get_guidance",
    "extract_chat_from_screenshots",
    "understand_screenshot_conversation",
    "analyze_screenshot_messages_for_revisions_and_guidance",
    "analyze_screenshot_communication_and_suggest",
    "reply_private",
    "reply_public_solo",
    "extract_user_preferences",
    "detect_lounge_intention",
    "generate_activity_recommendations",
    "generate_repair_vouchers",
    "generate_love_map_questions_for_profile",
    "generate_things_to_find_out",
]
